### PR TITLE
Reorganised and improved zone status

### LINKED ISSUE #114: Make the zone status field more useful
Following up on discussion #107, the zone status field needs a bit of attention.

The notion of a "passive" zone does not make much sense in the given context, and there are some other states that make sense, so the list of states a zone can have should be extended, e.g. to 

* Active
* Reserved
* Deprecated
* Parked

When a zone is not marked "Active", this should have an impact on the creation of PTR records if there are any address records in the zone. At least they should get flagged as inactive so that provisioning mechanisms based on Netbox DNS data can handle them appropriately (probably just ignoring them).

### PR DESCRIPTION
**Pull request by peteeckel**
* New zone status values ("passive" removed, new status "deprecated", "reserved" and "parked")
* Records in non-active zones are marked inactive in GUI and API
* PTR records for A/AAAA records in non-active zones are marked inactive in GUI and API

fixes #114

### CODE REVIEW

**Comment by peteeckel** [comment]
In fact, I had a much better solution for this, avoiding the use of a model method written in Python completely: It's possible to create a virtual "active" field for records using custom managers for the Zone and Record models. 

While this works perfectly, I could not get the tests "borrowed" from netbox/utilities/tests to succeeed on the unexpected "field". `validation_excludes_fields` unfortunately doesn't have any effect.

**Comment by peteeckel** [comment]
This is the (hopefully) much better version mentioned above.

Fixes to the tests were actually quite simple: The synthetic "active" field (that is actually an annotation computed from the zone state of the record and, if applicable, the associated address record) must be defined as read-only so the test code will not try to write to it.

Another issue is that the annotated object cannot be used in some contexts due to a constraint of PostgreSQL. Actually the solution is not extremely pretty - for the one case in which this issue arises (creating managed NS records from zone data) I included the standard object manager without the `active` annotation, which circumvents the issue.

The advantage is that the new `active` field for zones and records behaves mostly like a real model field, which means it can be used for sorting etc., and the python method `is_active`, which can lead to performance and memory issues with large datasets, is now replaced by a query executed in the database, which should be much more efficient.

**Comment by hatsat32** [comment]
Hi, Pete. I hope you are doing well.

Sorry for the late response. I've been a little busy the last few weeks.

Your changes look good.

I see some changes reflected in PR #106. Which should I merge first?

**Comment by peteeckel** [comment]
Hi Süleyman, 

thanks! I hope you all are well, too. I'm a bit busy myself, which explains me keeping relatively quiet ... but there are things in the works :-)

I adjusted the documentation in #106 to reflect the changes made in #115, so it makes sense to merge #115 first.

**Pull request merged**
