### PR TITLE
Add zones nested serializer to nameservers

### LINKED ISSUE #230: associated zones not visible on REST API nameservers endpoint
Description:

It is impossible to retrieve the related zones querying nameservers API, while the nested zone table in displayed in the Nameserver detail View. This makes me think that it has not been omitted due to performance concerns.
This search however is possible through the GraphQL with query like:
```
query{
  nameserver_list {
    name
    zones {
      name
    }
  }
}
```

How to implement:
add  NestedZoneSerializer as an attribute on NameServerSerializer

Database changes:
None as the relationship between zone and nameserver objects is already of type many-to-many

If you think it is worth implementation, I can try the PR

### PR DESCRIPTION
**Pull request by LuPo**
Fixes #230 
Nested serializer in read only mode

### CODE REVIEW

**Comment by peteeckel** [comment]
I have a pretty urgent one waiting myself, so let's hope approval comes soon.

By the way: The "fixes #230" must go into a comment to be processed automatically by GitHub, subject won't do :-)

**Comment by hatsat32** [comment]
Hi @LuPo . Thank you for your contribution! Can you please reformat the code with `psf/black` pls?

**Comment by peteeckel** [comment]
Hi @LuPo, if you're in a hurry and don't have the time to install and run psf/black: Likely the culprit is the extraneous space before "NestedZoneSerializer".

**Comment by LuPo** [comment]
Fixes #230. Thank you @hatsat32 and @peteeckel for your suggestions and your valuable work.

**Comment by peteeckel** [comment]
> Fixes #230 

Hrmph. That doesn't work either :-(

Possibly it has to go into the initial comment or there's something else I'm missing ... maybe the unapproved workflow. Could you try editing the initial comment?

**Comment by LuPo** [comment]
I found the documentation on the github [issue linking](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue). The keyword should go to the pull request description or a commit message in order to close the issue on a default branch upon successful merge. I saw that contributions to netbox are using often the former.

**Pull request merged**
