### PR TITLE
Compatibility update for NetBox 3.5

### LINKED ISSUE #293: NetBox 3.5 is incompatible with NetBox DNS 0.17.0
When upgrading to NetBox 3.5, NetBox will fail to start as long as NetBox DNS 0.17.0 is installed and enabled.

### PR DESCRIPTION
**Pull request by peteeckel**
This PR provides compatibility with NetBox 3.5.

Please note that starting from this release, NetBox DNS will no longer be compatible with NetBox 3.4 and lower. On the other hand, it requires NetBox 3.5 or higher.

If you are staying with NetBox 3.4.x please use NetBox DNS 0.17.0.

Fixes #293

### CODE REVIEW

**Comment by peteeckel** [comment]
Here we go - NetBox 3.5.0 was released today.

**Comment by vwbusguy** [comment]
I can verify that having Netbox DNS enabled when attempting a 3.5 upgrade does indeed break the upgrade.

**Comment by bouchardh** [comment]
Will this get merged or is there an easy way to test it?

Went back to 3.7.10 to keep this plugin active.

**Comment by vwbusguy** [comment]
> Went back to 3.7.10 to keep this plugin active.

I assume you meant 3.4.10?  If so, same here.

**Comment by vwbusguy** [comment]
Doesn't seem to bode well that their website is not resolvable:  https://auroraresearchlab.com

**Comment by peteeckel** [comment]
Not a good sign, I agree. I haven't heard from them lately ... 

I'll prepare some intermediate solution until things becom clearer. If Aurora really is out of business, I'll fork.

**Comment by peteeckel** [comment]
Have a look at discussion #298 for a quick remedy.

**Comment by peteeckel** [comment]
I guess we have a little problem. Nothing official from @hatsat32 and friends, but there was an update to the registration for auroraresearchlab.com on January 26th:
```
   Domain Name: AURORARESEARCHLAB.COM
   Registry Domain ID: 2475410830_DOMAIN_COM-VRSN
   Registrar WHOIS Server: whois.namesilo.com
   Registrar URL: http://www.namesilo.com
   Updated Date: 2023-01-26T10:40:03Z
   Creation Date: 2020-01-03T18:26:59Z
   Registry Expiry Date: 2024-01-03T18:26:59Z
   Registrar: NameSilo, LLC
   Registrar IANA ID: 1479
   Registrar Abuse Contact Email: abuse@namesilo.com
   Registrar Abuse Contact Phone: +1.4805240066
   Domain Status: clientTransferProhibited https://icann.org/epp#clientTransferProhibited
   Name Server: JOAN.NS.CLOUDFLARE.COM
   Name Server: LLOYD.NS.CLOUDFLARE.COM
   DNSSEC: unsigned
   URL of the ICANN Whois Inaccuracy Complaint Form: https://www.icann.org/wicf/
```
There are no members of the organisation "auroraresearchlab" listed in Github. 

And their DNS zone is gone:
```
 <<>> DiG 9.10.6 <<>> auroraresearchlab.com soa
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 16788
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;auroraresearchlab.com.		IN	SOA

;; Query time: 518 msec
;; SERVER: 2a00:19e0:3004:c06::c05:0#53(2a00:19e0:3004:c06::c05:0)
;; WHEN: Wed May 03 00:20:35 CEST 2023
;; MSG SIZE  rcvd: 50
```

Well ... that's it, I suppose.

**Comment by vwbusguy** [comment]
I suggest we continue on with your repo under a new Pypi name, such as "netbox-dns-ng", etc., assuming you're OK with owning it for now?

**Comment by bouchardh** [comment]
> > Went back to 3.7.10 to keep this plugin active.
> 
> I assume you meant 3.4.10? If so, same here.

yes, my bad...

**Pull request closed without merging**
